image: python:latest

# This folder is cached between builds (http://docs.gitlab.com/ce/ci/yaml/README.html#cache)
cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V

stages:
  - test
  - style
  - docs
  - deploy

pep8:
  stage: style
  before_script:
  - pip install -r requirements.txt
  script:
  - ./ci/pycodestyle_runner.sh
  artifacts:
    paths:
      - public/pycodestyle.txt

pylint:
  stage: style
  before_script:
  - pip install -r requirements.txt
  script:
  - ./ci/pylint_runner.sh
  artifacts:
    paths:
      - public/pylint.svg
      - public/pylint.html

test:
  stage: test
  before_script:
  - pip install -r requirements.txt
  script:
  - coverage run --source='.' manage.py test home
  - coverage report --omit="home/apps/*","home/validators.py","home/migrations/*","alpha_home/*","manage.py","home/test.py","home/receiver.py"
  - coverage html --omit="home/apps/*","home/validators.py","home/migrations/*","alpha_home/*","manage.py","home/test.py","home/receiver.py"
  - mkdir public
  - mv htmlcov public/coverage
  artifacts:
    paths:
      - public/coverage

sphinx:
  stage: docs
  before_script:
  - pip install -r requirements.txt
  script:
  - cd docs
  - make html
  - cd ..
  - mv docs/build/html public/docs
  artifacts:
    paths:
      - public/docs

