# Generated by Django 2.1.7 on 2019-05-19 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190518_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 20, 13, 3, 40, 809034, tzinfo=utc)),
        ),
    ]
