# Generated by Django 2.1.7 on 2019-05-20 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190519_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecovery',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 12, 43, 44, 999068, tzinfo=utc)),
        ),
    ]
